# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

### 1.1) Arithmetic

In [21]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([4, 5, 6, 7, 8, 9])

In [22]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [25]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

C:\Users\WAEL~1.MOH\AppData\Local\Temp/ipykernel_6608/1352063791.py:3: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# Also warning, but not an error instead infinity
1 / arr

C:\Users\WAEL~1.MOH\AppData\Local\Temp/ipykernel_6608/3632943242.py:2: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### 2.2) Logic

In [11]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [12]:
arr != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

**We can also do operations on 2-D arrays**

In [13]:
arr = np.random.randint(0,10, (3,3))
arr

array([[2, 7, 4],
       [0, 3, 8],
       [0, 0, 0]])

In [14]:
arr + 3

array([[ 5, 10,  7],
       [ 3,  6, 11],
       [ 3,  3,  3]])

In [15]:
arr - 2

array([[ 0,  5,  2],
       [-2,  1,  6],
       [-2, -2, -2]])

In [16]:
3 * arr

array([[ 6, 21, 12],
       [ 0,  9, 24],
       [ 0,  0,  0]])

In [17]:
arr

array([[2, 7, 4],
       [0, 3, 8],
       [0, 0, 0]])

In [18]:
arr + 3 * arr

array([[ 8, 28, 16],
       [ 0, 12, 32],
       [ 0,  0,  0]])

In [19]:
arr * arr

array([[ 4, 49, 16],
       [ 0,  9, 64],
       [ 0,  0,  0]])

array([[2, 7, 4],
       [0, 3, 8],
       [0, 0, 0]])

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [22]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
matrix = np.random.randint(0, 100, (5, 3))
matrix

array([[41, 50, 15],
       [21, 82, 87],
       [91, 33, 26],
       [59, 79, 71],
       [30, 18, 85]])

In [31]:
matrix.max(axis=0)
## axis = 0 Columns  
## axis = 1  rows

array([91, 82, 87])

### 2.1) max, min, average, sum

**max**

In [32]:
np.max(arr) #same as arr.max()

9

In [33]:
np.max(matrix)

91

In [34]:
np.max(matrix, axis=0)

array([91, 82, 87])

In [35]:
np.max(matrix, axis=1)

array([50, 87, 91, 79, 85])

**min**

In [36]:
np.min(arr) #same as arr.min()

0

In [37]:
np.min(matrix)

15

In [38]:
np.min(matrix, axis=0)

array([21, 18, 15])

In [39]:
np.min(matrix, axis=1)

array([15, 21, 26, 59, 18])

**average**

In [40]:
np.average(arr)

4.5

In [41]:
np.average(matrix)

52.53333333333333

In [42]:
np.average(matrix, axis=0)

array([48.4, 52.4, 56.8])

In [43]:
np.average(matrix, axis=1)

array([35.33333333, 63.33333333, 50.        , 69.66666667, 44.33333333])

**sum**

In [44]:
np.sum(arr)

45

In [45]:
np.sum(matrix)

788

In [46]:
np.sum(matrix, axis=0)

array([242, 262, 284])

In [47]:
np.sum(matrix, axis=1)

array([106, 190, 150, 209, 133])

### 2.2) sqrt, exp, log, sin

**power**

In [48]:
np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [49]:
np.power(matrix, 3)

array([[ 68921, 125000,   3375],
       [  9261, 551368, 658503],
       [753571,  35937,  17576],
       [205379, 493039, 357911],
       [ 27000,   5832, 614125]], dtype=int32)

**sqrt**

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.sqrt(matrix)

array([[6.40312424, 7.07106781, 3.87298335],
       [4.58257569, 9.05538514, 9.32737905],
       [9.53939201, 5.74456265, 5.09901951],
       [7.68114575, 8.88819442, 8.42614977],
       [5.47722558, 4.24264069, 9.21954446]])

**exp**

In [52]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [53]:
np.exp(matrix)

array([[6.39843494e+17, 5.18470553e+21, 3.26901737e+06],
       [1.31881573e+09, 4.09399696e+35, 6.07603023e+37],
       [3.31740010e+39, 2.14643580e+14, 1.95729609e+11],
       [4.20121040e+25, 2.03828107e+34, 6.83767123e+30],
       [1.06864746e+13, 6.56599691e+07, 8.22301271e+36]])

**log**

In [54]:
np.log(arr)

C:\Users\WAEL~1.MOH\AppData\Local\Temp/ipykernel_14000/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [55]:
np.log(matrix)

array([[3.71357207, 3.91202301, 2.7080502 ],
       [3.04452244, 4.40671925, 4.46590812],
       [4.51085951, 3.49650756, 3.25809654],
       [4.07753744, 4.36944785, 4.26267988],
       [3.40119738, 2.89037176, 4.44265126]])

### 2.3) sin, cos, tan

In [61]:
np.linspace(0, 360, 9)
 

array([  0.,  45.,  90., 135., 180., 225., 270., 315., 360.])

In [62]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [63]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

**sin**

In [64]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

**cos**

In [65]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

**tan**

In [66]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

### 2.4) dot product

In [70]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(vec1, mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[24 30 36]


In [71]:
vec1.dot(mat)

array([24, 30, 36])

# Great Job!

That's all we need to know for now!