# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(30,40)

In [3]:
#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [4]:
#Get a value at an index
arr[8]

38

In [5]:
#Get values in a range
arr[1:5]

array([31, 32, 33, 34])

In [6]:
#Get values in a range
arr[0:5]

array([30, 31, 32, 33, 34])

In [7]:
arr[:5]

array([30, 31, 32, 33, 34])

In [8]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [9]:
arr[3:7]

array([33, 34, 35, 36])

In [13]:
arr[3:7:2]

array([33, 35])

In [14]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [15]:
#Setting a value with index range (Broadcasting)
arr[2:5] = 100

#Show
arr

array([ 30,  31, 100, 100, 100,  35,  36,  37,  38,  39])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [23]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [24]:
# Getting individual element value
arr_2d[1, 0]

20

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [30]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[::-1,::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [35]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [36]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [37]:
#Set up matrix
arr2d = np.random.randint(1, 100, (10,10))
arr2d

array([[82, 32, 54, 50, 94, 95, 93, 29, 42, 74],
       [88, 46, 86, 57, 97, 39,  5, 98, 91, 24],
       [53, 55, 85, 76, 63, 50,  9, 96, 44, 17],
       [75,  4, 38, 37, 23, 74, 51, 53, 81, 99],
       [54, 93, 40, 19,  3, 10, 64, 76, 64, 33],
       [92, 51,  4, 85, 71, 63, 14, 89, 25, 18],
       [71,  4, 53, 16, 99, 74, 67, 93, 51, 32],
       [15,  4,  2, 65, 40, 19, 90, 92, 40, 41],
       [34, 85, 47, 32, 20, 42, 54, 41, 47,  8],
       [32, 66, 41,  2, 57, 38,  3, 21, 90, 17]])

Fancy indexing allows the following

In [38]:
arr2d[[1,4,6,8]]

array([[88, 46, 86, 57, 97, 39,  5, 98, 91, 24],
       [54, 93, 40, 19,  3, 10, 64, 76, 64, 33],
       [71,  4, 53, 16, 99, 74, 67, 93, 51, 32],
       [34, 85, 47, 32, 20, 42, 54, 41, 47,  8]])

In [39]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[71,  4, 53, 16, 99, 74, 67, 93, 51, 32],
       [54, 93, 40, 19,  3, 10, 64, 76, 64, 33],
       [53, 55, 85, 76, 63, 50,  9, 96, 44, 17],
       [15,  4,  2, 65, 40, 19, 90, 92, 40, 41]])

In [40]:
arr2d[[1,4,6,8], 2:5]

array([[86, 57, 97],
       [40, 19,  3],
       [53, 16, 99],
       [47, 32, 20]])

# Great Job!
